### Apiori Association
- One of the algorithms for Association

In [31]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [57]:
pd.set_option("display.max_rows",200)

In [58]:
dataset = pd.read_csv("/Users/rachanapandey/Desktop/study_materials/Data Science/Dataset/groceries.csv")
dataset.head()

,Items1,Items2,Items3,Items4,Items5,Items6,Items7,Items8,Items9,Items10,...,Items14,Items15,Items16,Items17,Items18,Items19,Items20,Items21,Items22,Items23
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
dataset.columns

Index(['Items1', 'Items2', 'Items3', 'Items4', 'Items5', 'Items6', 'Items7',
       'Items8', 'Items9', 'Items10', 'Items11', 'Items12', 'Items13',
       'Items14', 'Items15', 'Items16', 'Items17', 'Items18', 'Items19',
       'Items20', 'Items21', 'Items22', 'Items23'],
      dtype='str')

We need to make a list of list of what customers buy. [[a,b], [a,c,e]..] We do this to removoe the NaN values. NaN are the floating content. We will separate the string values and the floating values

In [60]:
dataset.shape

(700, 23)

In [61]:
# we want to run the loop up until the last row. technically 700 will be empty as it starts at 0-699 but count is 700
market = []
for i in range(0,dataset.shape[0]):
    cus = []
    for j in dataset.columns:
        if type(dataset[j][i]) == str: #if str, add it to customer
            cus.append(dataset[j][i])
        market.append(cus) #add the customer list to market

In [62]:
# now we use this market for analysis
market

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['fruit/vegetable juice'],
 ['fruit/vegetable juice'],

In [63]:
# importing to use the Counter function
import collections

In [64]:
# counter function helps us count the occurance of the str/char. Example below
collections.Counter(["a","a","a","s","s", "d"])

Counter({'a': 3, 's': 2, 'd': 1})

In [65]:
# To use Counter, we would have to convert the 2-D list to a single list, for which we use numpy

In [66]:
l = []
for i in market:
    for j in i:
        l.append(j)

In [68]:
# gives count of occurances of each element. Can use p.keys and .values() to see the result.
p = collections.Counter(l)

In [69]:
# creating a dictionary with the keys and values
d = {"Item Name":p.keys(), "values":p.values()}

In [71]:
#pd.DataFrame(d).sort_values(by=["values"], ascending=False)

In [72]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [73]:
tr = TransactionEncoder()
tr.fit(market)

/opt/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/externals/_numpydoc/docscrape.py:383: UserWarning: potentially wrong underline length...
Parameters
------------ in
Encoder class for transaction data in Python lists
...
  if not self._is_at_section():
/opt/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/externals/_numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length...
Attributes
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():
/opt/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/externals/_numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():

TransactionEncoder()

In [77]:
df = pd.DataFrame(tr.transform(market), columns=tr.columns_)
#df

In [78]:
from mlxtend.frequent_patterns import apriori

In [85]:
apriori(df, min_support=0.05, use_colnames=True).sort_values(by =["support"])

     support                                   itemsets
9   0.051429                     frozenset({margarine})
19  0.054286            frozenset({whipped/sour cream})
0   0.060000                          frozenset({beef})
22  0.064286  frozenset({other vegetables, whole milk})
23  0.064286        frozenset({rolls/buns, whole milk})
1   0.064286                  frozenset({bottled beer})
8   0.065714         frozenset({fruit/vegetable juice})
5   0.067143                        frozenset({coffee})
7   0.068571                   frozenset({frankfurter})
16  0.070000                 frozenset({shopping bags})
10  0.072857                    frozenset({newspapers})
6   0.074286                          frozenset({curd})
12  0.077143                        frozenset({pastry})
3   0.078571                   frozenset({canned beer})
15  0.081429                       frozenset({sausage})
18  0.092857                frozenset({tropical fruit})
4   0.092857                  frozenset({citrus fruit})
14  0.101429               frozenset({root vegetables})
21  0.115714                        frozenset({yogurt})
2   0.137143                 frozenset({bottled water})
17  0.160000                          frozenset({soda})
11  0.184286              frozenset({other vegetables})
13  0.218571                    frozenset({rolls/buns})
20  0.251429                    frozenset({whole milk})