### FP Growth Algorithm (Association Algo Learning)

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_rows", 500)

In [3]:
dataset = pd.read_csv("/Users/rachanapandey/Desktop/study_materials/Data Science/Dataset/groceries.csv")
dataset.head()

,Items1,Items2,Items3,Items4,Items5,Items6,Items7,Items8,Items9,Items10,...,Items14,Items15,Items16,Items17,Items18,Items19,Items20,Items21,Items22,Items23
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dataset.head()

,Items1,Items2,Items3,Items4,Items5,Items6,Items7,Items8,Items9,Items10,...,Items14,Items15,Items16,Items17,Items18,Items19,Items20,Items21,Items22,Items23
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dataset.shape

(700, 23)

In [7]:
market=[]
for i in range(0, dataset.shape[0]):
    cus = []
    for j in dataset.columns:
        if type(dataset[j][i])==str:
            cus.append(dataset[j][i])
        market.append(cus)

In [8]:
market

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['pot plants'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['whole milk', 'cereals'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['beef'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['chicken', 'tropical fruit'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['fruit/vegetable juice'],
 ['fruit/vegetable juice'],

In [11]:
l =[]
for i in market:
    for j in i:
        l.append(j)

In [12]:
import collections

In [13]:
p = collections.Counter(l)

In [14]:
d = {"Item Name": p.keys(), "Values": p.values()}

In [16]:
#pd.DataFrame(d).sort_values(by=["Values"], ascending=False)

In [18]:
# this is used to encode our data to True or False
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [19]:
tr = TransactionEncoder()
tr.fit(market)

/opt/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/externals/_numpydoc/docscrape.py:383: UserWarning: potentially wrong underline length...
Parameters
------------ in
Encoder class for transaction data in Python lists
...
  if not self._is_at_section():
/opt/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/externals/_numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length...
Attributes
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():
/opt/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/externals/_numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():

TransactionEncoder()

In [21]:
df = pd.DataFrame(tr.transform(market), columns=tr.columns_)

### Applying FP Growth

In [23]:
from mlxtend.frequent_patterns import fpgrowth

In [26]:
fpgrowth(df, min_support=0.05, max_len=3,use_colnames=True ).sort_values(by=["support"])

     support                                   itemsets
1   0.051429                     frozenset({margarine})
21  0.054286            frozenset({whipped/sour cream})
11  0.060000                          frozenset({beef})
22  0.064286  frozenset({whole milk, other vegetables})
8   0.064286                  frozenset({bottled beer})
23  0.064286        frozenset({rolls/buns, whole milk})
15  0.065714         frozenset({fruit/vegetable juice})
4   0.067143                        frozenset({coffee})
13  0.068571                   frozenset({frankfurter})
20  0.070000                 frozenset({shopping bags})
14  0.072857                    frozenset({newspapers})
10  0.074286                          frozenset({curd})
16  0.077143                        frozenset({pastry})
18  0.078571                   frozenset({canned beer})
19  0.081429                       frozenset({sausage})
0   0.092857                  frozenset({citrus fruit})
3   0.092857                frozenset({tropical fruit})
17  0.101429               frozenset({root vegetables})
2   0.115714                        frozenset({yogurt})
9   0.137143                 frozenset({bottled water})
12  0.160000                          frozenset({soda})
6   0.184286              frozenset({other vegetables})
7   0.218571                    frozenset({rolls/buns})
5   0.251429                    frozenset({whole milk})